version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  postgres:
    image: postgres:16
    container_name: virtualbookstore-db
    restart: always
    ports:
      - "5432:5432"  # DataGrip bu porttan erişecek
    environment:
      POSTGRES_DB: virtualbookstore
      POSTGRES_USER: dincdev
      POSTGRES_PASSWORD: bookpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  esdata: